name: Generar Árbol de Dispositivo TWRP

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or any supported version >=3.9,<4.0

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install sebaubuntu_libs
          # pip install -r requirements.txt  # if you have other dependencies

      # Continue with additional steps...
      - name: Instalar twrpdtgen
        run: |
          python -m pip install --upgrade pip
          python -m pip install twrpdtgen==2.2

      - name: Descargar vendor_boot
        run: |
          wget -O vendor_boot_b.bin "https://files.catbox.moe/ru8mxx.bin"

      - name: Generar Árbol de Dispositivo
        run: |
          mkdir -p out
          python -m twrpdtgen -o ./out/ vendor_boot_b.bin

      - name: Comprimir Resultado
        run: |
          cd ./out
          zip -r -9 DeviceTree.zip ./*

      - name: Subir Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./out/DeviceTree.zip
          name: TWRP_Device_Tree-${{ github.run_id }}
          tag_name: twrp-dt-${{ github.run_id }}
          body: Árbol de dispositivo generado para Infinix X6525.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
